name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/granite-react
